//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyTourDatabaseEntities : DbContext
    {
        public HappyTourDatabaseEntities()
            : base("name=HappyTourDatabaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<Office> Offices { get; set; }
        public virtual DbSet<OnHoliday> OnHolidays { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Person> People { get; set; }
        public virtual DbSet<Place> Places { get; set; }
        public virtual DbSet<PLTCON> PLTCONs { get; set; }
        public virtual DbSet<Program> Programs { get; set; }
        public virtual DbSet<PRTCON> PRTCONs { get; set; }
        public virtual DbSet<Report> Reports { get; set; }
        public virtual DbSet<Tour> Tours { get; set; }
        public virtual DbSet<Tourguide> Tourguides { get; set; }
        public virtual DbSet<User> Users { get; set; }
    }
}
