//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA
{
    using System;
    using System.Collections.Generic;
    
    public partial class Office
    {
        public int OfficeID { get; set; }
        public string OfficeName { get; set; }
        public decimal TaxID { get; set; }
        public string AddressCity { get; set; }
        public string AddressZip { get; set; }
        public string AddressFree { get; set; }
        public string AddressCountry { get; set; }
    }
}
