//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyTourManager
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HappyDataBaseEntities : DbContext
    {
        public HappyDataBaseEntities()
            : base("name=HappyDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Customer> Customer { get; set; }
        public virtual DbSet<Language> Language { get; set; }
        public virtual DbSet<Office> Office { get; set; }
        public virtual DbSet<OnHoliday> OnHoliday { get; set; }
        public virtual DbSet<Order> Order { get; set; }
        public virtual DbSet<Person> Person { get; set; }
        public virtual DbSet<Place> Place { get; set; }
        public virtual DbSet<Program> Program { get; set; }
        public virtual DbSet<Report> Report { get; set; }
        public virtual DbSet<Tour> Tour { get; set; }
        public virtual DbSet<Tourguide> Tourguide { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
