//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HappyTourManager
{
    using System;
    using System.Collections.Generic;
    
    public partial class PRTCON
    {
        public int PRTCONID { get; set; }
        public int TourID { get; set; }
        public int ProgramID { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual Tour Tour { get; set; }
    }
}
